# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  tinykvserver:
    image: tinykvserver
    build:
      context: .
      dockerfile: TinyKV.Server/Dockerfile
      args:
        - configuration=Debug
    ports:
      - 5009:5009
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
